# Generated by Django 5.0.4 on 2024-04-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avilable_for',
            field=models.TimeField(null=True),
        ),
    ]
